# Generated by Django 5.2.7 on 2026-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Custid', models.IntegerField(primary_key=True, serialize=False)),
                ('Accno', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Dob', models.CharField(max_length=20)),
                ('Phno', models.BigIntegerField()),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Id', models.CharField()),
                ('Date', models.DateField()),
                ('Accno', models.IntegerField()),
                ('Type', models.CharField(choices=[('d', 'Deposit'), ('w', 'Withdraw')], max_length=1)),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
