# Generated by Django 5.2.7 on 2026-02-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Transaction_Id',
        ),
    ]
